### ISSUE TITLE
undefined method default_session

### ISSUE THREAD

**Issue by romanoff** [td-berlin/mongoid_cleaner#9]
Faced following issue:

```   
  Failure/Error:
       MongoidCleaner.cleaning do
         example.run
     
     NoMethodError:
       undefined method `default_session' for Mongoid:Module
     # /home/aromanov/.gems/gems/mongoid_cleaner-1.1.0/lib/mongoid_cleaner.rb:32:in `session'
     # /home/aromanov/.gems/gems/mongoid_cleaner-1.1.0/lib/mongoid_cleaner.rb:38:in `collections_filter'
     # /home/aromanov/.gems/gems/mongoid_cleaner-1.1.0/lib/mongoid_cleaner.rb:49:in `collections'
     # /home/aromanov/.gems/gems/mongoid_cleaner-1.1.0/lib/mongoid_cleaner.rb:56:in `collections_with_options'
     # /home/aromanov/.gems/gems/mongoid_cleaner-1.1.0/lib/mongoid_cleaner.rb:67:in `drop'
     # /home/aromanov/.gems/gems/mongoid_cleaner-1.1.0/lib/mongoid_cleaner.rb:83:in `public_send'
     # /home/aromanov/.gems/gems/mongoid_cleaner-1.1.0/lib/mongoid_cleaner.rb:83:in `clean'
     # /home/aromanov/.gems/gems/mongoid_cleaner-1.1.0/lib/mongoid_cleaner.rb:87:in `cleaning'
     # ./spec/spec_helper.rb:27:in `block (2 levels) in <top (required)>'
```

Using mongoid 5.0.2, mongoid_cleaner 1.1.0, rails 4.2.5

**Comment by maciejmajewski** [comment]
It's fixed in https://github.com/td-berlin/mongoid_cleaner/pull/8

I will release 1.2.0 with this fix.

**Comment by maciejmajewski** [comment]
Done: https://rubygems.org/gems/mongoid_cleaner/versions/1.2.0, closing this issue.
